### ISSUE TITLE
singularity image generation is broken

### ISSUE THREAD

**Issue by prudhomm** [feelpp/singularity#3]
https://buildkite.com/feelpp/feelpp-singularity/builds/315#eb34d00c-e243-4dd1-ba5c-79d593d77db5

**Comment by prudhomm** [comment]
This issue is part of the 0.104 release [1]

 1. https://app.zenhub.com/workspace/o/feelpp/feelpp/reports?report=release&release=5adc587ad59f63705a6b4897

**Comment by gdolle** [comment]
It certainly due to a change of docker name format. I'll fix that.
(PS: I transform the "latest" tag to the longest image name.)

**Comment by gdolle** [comment]
I talked maybe too fast. I think it's rather a cache corruption (Due to NFS. Just cleaning the cache should solve the problem). I'll keep you up to date.

**Comment by gdolle** [comment]
I confirm my last comment. Fixed.
