### ISSUE TITLE
[Fluid Toolbox / Sequential / Singularity on Atlas] Lots of threads created

### ISSUE THREAD

**Issue by prudhomm** [feelpp/singularity#5]
@francoisdh commented on [Wed Jun 27 2018](https://github.com/feelpp/feelpp/issues/1190)

A lot of threads are created when using the fluid toolbox in sequential using Singularity (tested on atlas node 3):

Using 

`feelpp_feelpp-toolboxes-master-v0.105.0-ubuntu-16.04.simg`,

testing with 

`feelpp_toolbox_fluid --case "github:{repo:toolbox,path:examples/modules/cfd/examples/spring}"`

and monitoring using `htop` shows 48 threads running at 100% eventually. This matches the number of logical cores of the node. 

---

@francoisdh commented on [Wed Jun 27 2018](https://github.com/feelpp/feelpp/issues/1190#issuecomment-400717192)

This is solved by limiting the number of OpenMP threads:

```
export OMP_NUM_THREADS=1
```

Using this fix shows no difference in actual execution times.

---

@prudhomm commented on [Wed Jun 27 2018](https://github.com/feelpp/feelpp/issues/1190#issuecomment-400723330)

Have you compared the perfs with the native version using the modules from @vincentchabannes ? 

---

@prudhomm commented on [Thu Jun 28 2018](https://github.com/feelpp/feelpp/issues/1190#issuecomment-400985976)

@francoisdh in docker we have this 
```
export OPENBLAS_NUM_THREADS=1
export OPENBLAS_VERBOSE=0
```
could you check what is set in singularity ? We may have to modify singularity environment to fix this issue

**Comment by francoisdh** [comment]
@prudhomm Sorry, I have not checked with the modules yet, I will try today. About the environment variables, none of them are set:

```
[singularity]: derhovsepian@atlas3:~> env | grep OPENBLAS_NUM_THREADS
[singularity]: derhovsepian@atlas3:~> env | grep OPENBLAS_VERBOSE
[singularity]: derhovsepian@atlas3:~> 
```

**Comment by prudhomm** [comment]
We have to set them in the singularity environment file

**Comment by prudhomm** [comment]
@francoisdh a new singularity image is available with a possible fix. could you test it ?
see buildkite https://buildkite.com/feelpp/feelpp-singularity/builds/422#b98afca8-5fb0-4f25-98cc-3df2016f5daf

**Comment by prudhomm** [comment]
@francoisdh I tested and it seems that it is all right now

**Comment by prudhomm** [comment]
I set `OPENBLAS_NUM_THREAD=1` in singularity env like in docker

**Comment by francoisdh** [comment]
For the record, on atlas:

- By using the latest version of the modules `feelpp-toolboxes/v0.105.0_gcc640_openmpi1107`, the problem is not present. About the same number of threads are still spawned, but they remain idle.

- Using the latest image `feelpp_feelpp-toolboxes-master-v0.105.0-ubuntu-16.04.simg` shows no problem either.

However, I should mention that in both cases, neither `env` nor e.g. `echo $OPENBLAS_NUM_THREAD` showed any of the aforementioned variable. Is this expected ?

**Comment by prudhomm** [comment]
You have to test 0.106

**Comment by prudhomm** [comment]
@francoisdh test this one : https://girder.math.unistra.fr/api/v1/item/5b3578d8b0e9570499f67538/download

**Comment by francoisdh** [comment]
I tested with `feelpp_feelpp-toolboxes-master-v0.106.0-alpha.1-ubuntu-16.04.simg` on atlas3 too:

- No environment variables set by default. I can not see them using the previously mentioned commands.
- 48 threads spawned, idle most of the time, but 100% active near the end of the process, during the solver iterations (this happens after about 50s). To be clear, this makes the main thread run at 4800% for a few (real time) seconds.

- Now if I manually use `export OMP_NUM_THREADS=1` in the container, I only get 3 additional threads, and they remain idle for the whole simulation.

**Comment by prudhomm** [comment]
@francoisdh wrong image. Use develop 106

**Comment by francoisdh** [comment]
Thanks. In `feelpp_feelpp-toolboxes-develop-v0.106.0-alpha.1-ubuntu-16.04.simg`, the OPENBLAS variables are set and only one of the four thread is really used.
I will now test with more demanding cases, where the useless threads maxing out all the cores were actually slowing the whole process down.
